<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>NightlyDawn.Storage</AssemblyName>
    <RootNamespace>NightlyDawn.Storage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NightlyDawn.Core\NightlyDawn.Core.csproj" />
  </ItemGroup>

</Project>
